# Generated by Django 4.2.7 on 2023-11-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_text_up', models.TextField(verbose_name='Text to the left of the logo: ')),
                ('section_text_down', models.TextField(verbose_name='Text to the below the logo: ')),
            ],
            options={
                'verbose_name': 'Section in card',
                'verbose_name_plural': 'Sections in cards',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_company', models.ImageField(upload_to='cards/logos/', verbose_name='Логотип компании')),
                ('section_text', models.ManyToManyField(to='main_page.sectionincard', verbose_name='dfhf')),
            ],
        ),
    ]
