# Generated by Django 4.2.7 on 2023-11-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_card_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title_company',
            field=models.CharField(default=2, max_length=120, verbose_name='Название компании'),
            preserve_default=False,
        ),
    ]
