version: '3.3'


services:
  back-end:
    user: "root"
    build:
      context: ./src
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput  && python manage.py makemigrations && python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --access-logfile -"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "8000"
    env_file:
    - ./src/.env/



volumes:
  static_volume:
  media_volume: