# Generated by Django 4.2.7 on 2023-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='drop_down_info',
        ),
        migrations.AddField(
            model_name='form',
            name='drop_down_info',
            field=models.ManyToManyField(to='form.dropdownside', verbose_name='drop down data'),
        ),
    ]
