# Generated by Django 4.2.7 on 2023-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_form_drop_down_info_form_drop_down_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='phone_number',
            field=models.CharField(default=771478853, max_length=20, verbose_name='number'),
            preserve_default=False,
        ),
    ]
